### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hidahua** [yidun/activity-protection-demo#7]
function convert_null($params) {
    $new_params = array();
    foreach ($params as $key => $value) {
        $utf8s[$key] = is_null($value) ? '' : $value;
    }
    return $new_params;
}

=>

function convert_null($params) {
    $new_params = array();
    foreach ($params as $key => $value) {
        $new_params[$key] = is_null($value) ? '' : $value;
    }
    return $new_params;
}

**Comment by yd-dev** [comment]
fixed
